; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = master_esp

[env]
monitor_speed = 921600
upload_port = auto
platform = espressif32 @ 6.12.0 
framework = arduino
board = esp32-s3-devkitc-1

[env:master_esp]
build_flags = 
	${env.build_flags}
	-D IS_MASTER
	-I src/master
build_src_filter = +<*> -<slave/> +<master/> +<shared/>



lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.2
	zz-cat/CRSFforArduino@^2025.12.11
	adafruit/Adafruit LSM6DS@^4.7.4
	madhephaestus/ESP32Servo@^3.1.3

[env:slave_esp]
build_flags = 
	${env.build_flags}
	-D IS_SLAVE
	-I src/slave
build_src_filter = +<*> -<master/> +<slave/>
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.2
	arduino-libraries/Arduino_LSM6DSOX@^1.1.2
	adafruit/Adafruit LSM6DS@^4.7.4
	madhephaestus/ESP32Servo@^3.1.3
